server:
  port: 9291
spring:
  application:
    name: market
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    password:
  mvc:
    async:
      request-timeout: 20000
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    cn.dingli.market.mapper: debug

